[package]
name = "fbot_vss_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bytes = "1.1.0"
prost = "0.10"
prost-types = "0.10"


[build-dependencies]
prost-build = "0.10.4"